### ISSUE TITLE
制空権シミュレータでデータ更新ができない

### ISSUE THREAD

**Issue by pandamantts** [ElectronicObserverEN/ElectronicObserver#232]
サブウィンドウ「艦隊」から開く制空権シミュレータで、艦隊と基地航空隊のデータ更新が以前と同じようにはできないようになってしまいました。アップデートの影響かと思うのですが、改善できますでしょうか。

七四式電子観測儀四七型改（ver. 5.1.11.0-2022/08/23 Release）.NET 6.0.7

**Comment by myangelkamikaze** [comment]
Ah, looks like this broke because we extended the deckbuilder format. I opened an issue in the air control simulator repository to see if the extended format will be supported, or if we should revert to the basic format. https://github.com/noro6/kc-web/issues/5

If noro decides to support the extended format, this will be fixed without any update from our side needed.
If he decides not to support the extended format, we'll make a hotfix release for this.

**Comment by myangelkamikaze** [comment]
Noro added support for the extended format, and I confirmed that the fleet export works correctly now.
Thanks for reporting.
