### ISSUE TITLE
Request : add switching sound on/off by keyboard

### ISSUE THREAD

**Issue by xefat** [ElectronicObserverEN/ElectronicObserver#233]
ツールの更新、ありがとうございます。
以前はキーボードの"F7"キーで音声のON/OFFができていたのですが、
バージョン5.1.10以降(5.1.11含む)、機能しなくなってしまいました。
私はプレイ中(出撃中も)、よくこの機能を使っていたので、今も
バージョン5.1.9を使用し続けています。
そこで、再度この機能を実装していただけるよう、要望いたします。

Thank you for updating application.
5.1.10&5.1.11 sound on/off cannot be switched by "F7" key, so now
I still use 5.1.9.
Please enable this sound control function again.

**Comment by myangelkamikaze** [comment]
It looks like it only doesn't work the first time. If you manually mute/unmute with your mouse first, F7 will work after that. We'll look at what the problem could be.

**Comment by xefat** [comment]
Thank you for reply.
I checked with 5.1.11.
I unmute, then restart EO --- F7 key worked.
I mute, then restart EO --- F7 key not worked.
In that case, I cannot control with mouse because "Microsoft Edge WebView2"
is not listed on Windows sound config.

**Comment by myangelkamikaze** [comment]
The fix will be available in the next release.

**Comment by xefat** [comment]
I will be waiting for the release, thank you.

**Comment by myangelkamikaze** [comment]
Ah, also about your analysis above...
Yeah, I can reproduce the exact same thing as you.
"Microsoft Edge WebView2" not being listed in Windows sound config is actually the reason why F7 doesn't work.
So when you start EO muted, you need to first click the mute icon, so that the sound process gets created. Once you can see it in the Windows sound config, it should work normally.

So in 5.1.11:
Unmute, then restart EO --- F7 key works.
Mute, then restart EO --- F7 key doesn't work.
Mute, then restart EO, then click the mute icon --- F7 key works.
![image](https://user-images.githubusercontent.com/40002167/186679058-1174a487-6496-4467-bcf1-2e225526f17f.png)

In 5.1.12 it should work without clicking the icon first.

**Comment by xefat** [comment]
I'm sorry, I couldn't find out that because I usually hide "tool bar" for saving layout space.
Now I use 5.1.11. It works fine!

**Comment by myangelkamikaze** [comment]
I made a new preview release with the fix: https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.1.12-preview2

**Comment by xefat** [comment]
I have tried the release.
It works perfectly, so I no longer need to open/close "tool bar".
Thank you for your prompt response!
