### ISSUE TITLE
任務C44小艦艇群演習強化任務のカウンターが正しくカウントされない

### ISSUE THREAD

**Issue by detsuku** [ElectronicObserverEN/ElectronicObserver#261]
I achieved 3 wins in the exercise and when I look at the list of missions, the counter is 4/4.
The game shows over 80% achieved.
<img width="1099" alt="スクリーンショット 2022-12-02 124359" src="https://user-images.githubusercontent.com/77409739/205210270-6850f102-ce57-4a47-8a05-25e1128fc8ae.png">

**Comment by Heinrike** [comment]
When C44 is at 80% completion, opening the quests screen will cause quest progress for C44 to jump to 4/4 in EO. Even if quest progress is reset manually, progress for C44 will jump back to 4/4 every time the quest screen is opened. I believe EO might be wrongly interpreting 80% completion as 4/4 instead of 3/4 for some reason.

**Comment by myangelkamikaze** [comment]
Yeah, there's some extra logic to try to interpret progress that was done without EO knowing (for example, playing on your phone).
3/4 would be 75%, and cause 80% is more than that it tries to round up, but it's obviously a bug in this case.

**Comment by myangelkamikaze** [comment]
Should be fixed now, the fix will be available in 5.2.3.

**Comment by Heinrike** [comment]
Same bug happens for C53, presumably for the same reason

**Comment by myangelkamikaze** [comment]
Yup, same reason, but the fix I added will work for that one too.
Though right after release, I noticed that the fix breaks some of the older quest progress.
![image](https://user-images.githubusercontent.com/40002167/221395882-53acf387-0686-4396-a0b7-d65c954a7c3e.png)

In the released version, the quests from the picture above will have their progress decreased from 2 to 1.
That will be fixed in the next version.
