### ISSUE TITLE
Quest progress

### ISSUE THREAD

**Issue by xefat** [ElectronicObserverEN/ElectronicObserver#325]
Thank you for your continuous updating.

It seems like there are some cases quest progress fixed incorrectly.
e.g. Sink 2 Transport Ships
       Quest Bd5:敵補給艦を3隻撃沈せよ！ progress 2/3
       Open Kancolle Quest Window (displays 50%以上達成)
       Progress changed to 1/3
It happens after ver5.2.3.0, probably.

**Comment by myangelkamikaze** [comment]
Yeah, I described it in a related issue: https://github.com/ElectronicObserverEN/ElectronicObserver/issues/261#issuecomment-1445279722
The fix is available in the latest preview release: https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.4-preview1
Full release (including auto update) will probably be available on Saturday.

**Comment by myangelkamikaze** [comment]
Okay, just looked at the code again and apparently I missed Bd5...
It will be fixed in the 5.2.4 release on Saturday.

**Comment by xefat** [comment]
I got it!
I think quest F8: 艦娘「建造」艦隊強化！ (not listed in the picture of #261) might be the same too.

**Comment by myangelkamikaze** [comment]
Good catch, add it in too.

**Comment by xefat** [comment]
Okay, then I will be waiting for the next release, thank you.

**Comment by xefat** [comment]
I have completed a few old quests with new release.
It works fine, thank you!

**Comment by myangelkamikaze** [comment]
Nice, thanks for telling!
