### ISSUE TITLE
EXP calculator showing extra incorrect rows

### ISSUE THREAD

**Issue by Nobuchina** [ElectronicObserverEN/ElectronicObserver#347]
The "no. of battles" column is shown as if the exp is set to 1.
<img width="637" alt="20230405_104649" src="https://user-images.githubusercontent.com/98725028/229968815-05446b43-391c-46d9-8d4b-bd212c8d8c65.png">

The correct rows are shown if scrolled further down after Lv175:
<img width="638" alt="20230405_105104" src="https://user-images.githubusercontent.com/98725028/229969187-42db1f2c-d693-490a-983d-c3c986a806b8.png">

**Comment by myangelkamikaze** [comment]
Fixed in https://github.com/ElectronicObserverEN/ElectronicObserver/commit/ce827c230f974eb1f99befb2cb0c1659455c659f
The fix is available in the latest preview release: https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.6-preview1

Full release will probably happen after the event.
