### ISSUE TITLE
艦隊サブウィンドウの大破艦の点滅（母港時）

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#390]
5.2.10の変更で大破した艦が艦隊サブウィンドウで点滅表示されるようになりましたが、設定の艦隊サブウィンドウの「大破時に点滅させる」のチェックを外しても母港での点滅が止まりません。　出撃中に点滅する仕様は理解しています。

**Comment by myangelkamikaze** [comment]
Yeah, that's a bug. We already fixed it and the fix is available in 5.2.11 preview 1.
Preview versions aren't available via automatic update and must be downloaded manually. The full release will probably be in a few weeks.
https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.11-preview1
