### ISSUE TITLE
ライトテーマ時に徹甲弾アイコンの視認性が著しく低い

### ISSUE THREAD

**Issue by nelie-b-lasfolt** [ElectronicObserverEN/ElectronicObserver#517]
黒縁がほしいです
![image](https://github.com/user-attachments/assets/2046b13b-31e8-40de-9fef-ce43f6b350a0)

**Comment by myangelkamikaze** [comment]
https://twitter.com/74EOEN/status/1865733293662212383
This is already fixed, the fix will be available in the next release. You can download the latest preview if you'd like the fix right away, instead of waiting for the full release.
https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.3.10-preview1
